CREATE TABLE BOOKR_AUTHORIZATION (
  principalName VARCHAR(255) NOT NULL,
  person_id     VARCHAR(255) NOT NULL,
  PRIMARY KEY (person_id)
);
ALTER TABLE BOOKR_AUTHORIZATION ADD CONSTRAINT UK_PRINCIPALNAME UNIQUE (principalName);

CREATE TABLE BOOKR_AUTHORIZATION_ROLE (
  authorization_id VARCHAR(255) NOT NULL,
  role             VARCHAR(255)
);

CREATE TABLE BOOKR_BOOKING (
  id          VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  "end"       TIMESTAMP    NOT NULL,
  start       TIMESTAMP    NOT NULL,
  person_id   VARCHAR(255) NOT NULL,
  project_id  VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE BOOKR_PASSWORD (
  authorization_id VARCHAR(255) NOT NULL,
  password         VARCHAR(255) NOT NULL,
  PRIMARY KEY (authorization_id)
);

CREATE TABLE BOOKR_PERSON (
  id   VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);
ALTER TABLE BOOKR_PERSON ADD CONSTRAINT UK_NAME UNIQUE (name);

CREATE TABLE BOOKR_PROJECT (
  id   VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE BOOKR_PROJECT_PERSON (
  project_id VARCHAR(255) NOT NULL,
  person_id  VARCHAR(255) NOT NULL,
  PRIMARY KEY (project_id, person_id)
);

ALTER TABLE BOOKR_AUTHORIZATION ADD CONSTRAINT FK_PERSON FOREIGN KEY (person_id) REFERENCES BOOKR_PERSON;
ALTER TABLE BOOKR_AUTHORIZATION_ROLE ADD CONSTRAINT FK_AUTHORIZATION FOREIGN KEY (authorization_id) REFERENCES BOOKR_AUTHORIZATION;
ALTER TABLE BOOKR_BOOKING ADD CONSTRAINT FK_PERSON FOREIGN KEY (person_id) REFERENCES BOOKR_PERSON;
ALTER TABLE BOOKR_BOOKING ADD CONSTRAINT FK_PROJECT FOREIGN KEY (project_id) REFERENCES BOOKR_PROJECT;
ALTER TABLE BOOKR_PASSWORD ADD CONSTRAINT FK_AUTHORIZATION FOREIGN KEY (authorization_id) REFERENCES BOOKR_AUTHORIZATION;
ALTER TABLE BOOKR_PROJECT_PERSON ADD CONSTRAINT FK_PERSON FOREIGN KEY (person_id) REFERENCES BOOKR_PERSON;
ALTER TABLE BOOKR_PROJECT_PERSON ADD CONSTRAINT FK_PROJECT FOREIGN KEY (project_id) REFERENCES BOOKR_PROJECT;