INSERT INTO BOOKR_PERSON("ID", "PRINCIPALNAME") VALUES ('1', 'the user');
INSERT INTO BOOKR_PERSON("ID", "PRINCIPALNAME") VALUES ('2', 'the manager');
INSERT INTO BOOKR_PERSON("ID", "PRINCIPALNAME") VALUES ('3', 'the administrator');

INSERT INTO BOOKR_ROLE("PERSON_ID", "TYPE") VALUES ('1', 'USER');
INSERT INTO BOOKR_ROLE("PERSON_ID", "TYPE") VALUES ('2', 'MANAGER');
INSERT INTO BOOKR_ROLE("PERSON_ID", "TYPE") VALUES ('2', 'USER');
INSERT INTO BOOKR_ROLE("PERSON_ID", "TYPE") VALUES ('3', 'ADMINISTRATOR');

INSERT INTO BOOKR_PROJECT("ID", "NAME") VALUES ('1', 'ultimate project');
INSERT INTO BOOKR_PROJECT("ID", "NAME") VALUES ('2', 'weird project');
INSERT INTO BOOKR_PROJECT("ID", "NAME") VALUES ('3', 'funny project');

INSERT INTO BOOKR_BOOKING("ID", "PROJECT_ID", "PERSON_ID", "DESCRIPTION", "START", "END") VALUES ('1', '1', '1', 'the description 1', CURRENT_DATE(), CURRENT_DATE());
INSERT INTO BOOKR_BOOKING("ID", "PROJECT_ID", "PERSON_ID", "DESCRIPTION", "START", "END") VALUES ('2', '2', '2', 'the description 2', CURRENT_DATE(), CURRENT_DATE());
INSERT INTO BOOKR_BOOKING("ID", "PROJECT_ID", "PERSON_ID", "DESCRIPTION", "START", "END") VALUES ('3', '2', '1', 'the description 3', CURRENT_DATE(), CURRENT_DATE());
INSERT INTO BOOKR_BOOKING("ID", "PROJECT_ID", "PERSON_ID", "DESCRIPTION", "START", "END") VALUES ('4', '1', '2', 'the description 4', CURRENT_DATE(), CURRENT_DATE());
