INSERT INTO BOOKR_PERSON("ID", "PRINCIPALNAME") VALUES ('1', 'first');
INSERT INTO BOOKR_PERSON("ID", "PRINCIPALNAME") VALUES ('2', 'second');


INSERT INTO BOOKR_ROLE("PERSON_ID", "TYPE") VALUES ('1', 'USER');
INSERT INTO BOOKR_ROLE("PERSON_ID", "TYPE") VALUES ('1', 'MANAGER');
INSERT INTO BOOKR_ROLE("PERSON_ID", "TYPE") VALUES ('2', 'ADMINISTRATOR');
